# Generated by Django 5.1.5 on 2025-02-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_new_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='new_slug',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
