# Generated by Django 5.1.5 on 2025-02-17 05:26

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_category_slug_alter_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default_profile_pic.jpg', null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=3, editable=False, populate_from='title', unique=True),
            preserve_default=False,
        ),
    ]
